In [2]:
import pandas as pd

In [3]:
# Series

data = [1,2,3,4,5]
series = pd.Series(data)
print('Series \n', series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
# series from dictionary

data = {'a':10,
        'b':20,
        'c':30}

series_dict = pd.Series(data)
print('Series From Dictionary \n', series_dict)

Series From Dictionary
 a    10
b    20
c    30
dtype: int64

In [6]:
data = [1,3,5,7,9]
index = ['a','b','c','d','e']

pd.Series(data, index = index)

a    1
b    3
c    5
d    7
e    9
dtype: int64

In [3]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [6]:
# DataFrame

# creating a dataframe from dictionary

data = {
    'Name' : ['Bruce', 'Clark', 'Harvey'],
    'Age' : [34,67,54],
    'City' : ['Gotham', 'Metropolis', 'NYC']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age        City
0   Bruce   34      Gotham
1   Clark   67  Metropolis
2  Harvey   54         NYC
<class 'pandas.core.frame.DataFrame'>

In [7]:
# Create a Data Frame from a List of Dictionaries

data = [
    {'Name' :'Bruce', 'Age' : 35, 'City' : 'Gotham'},
    {'Name' :'Thanos', 'Age' : 124, 'City' : 'Titan'},
    {'Name' :'Thor', 'Age' : 500, 'City' : 'Asgard'},

]

df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age    City
0   Bruce   35  Gotham
1  Thanos  124   Titan
2    Thor  500  Asgard
<class 'pandas.core.frame.DataFrame'>

In [8]:
df = pd.read_csv('insurance.csv')
print(df.head(5))

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [9]:
df.tail(5)

      age     sex   bmi  children smoker     region  expenses
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

In [11]:
# accessing data from dataframe
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [13]:
df['age']

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [14]:
type(df['age'])

pandas.core.series.Series

In [15]:
df.loc[0]

age                19
sex            female
bmi              27.9
children            0
smoker            yes
region      southwest
expenses     16884.92
Name: 0, dtype: object

In [16]:
df.iloc[0]

age                19
sex            female
bmi              27.9
children            0
smoker            yes
region      southwest
expenses     16884.92
Name: 0, dtype: object

In [18]:
df.iloc[0][1]

C:\Users\razvi\AppData\Local\Temp\ipykernel_25048\2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

'female'

In [ ]:
# data manipulation
# remove a column
df.drop('children', axis=1)

      age     sex   bmi smoker     region  expenses
0      19  female  27.9    yes  southwest  16884.92
1      18    male  33.8     no  southeast   1725.55
2      28    male  33.0     no  southeast   4449.46
3      33    male  22.7     no  northwest  21984.47
4      32    male  28.9     no  northwest   3866.86
...   ...     ...   ...    ...        ...       ...
1333   50    male  31.0     no  northwest  10600.55
1334   18  female  31.9     no  northeast   2205.98
1335   18  female  36.9     no  southeast   1629.83
1336   21  female  25.8     no  southwest   2007.95
1337   61  female  29.1    yes  northwest  29141.36

[1338 rows x 6 columns]

In [22]:
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [23]:
df.drop('children', axis=1, inplace=True)

In [24]:
df

      age     sex   bmi smoker     region  expenses
0      19  female  27.9    yes  southwest  16884.92
1      18    male  33.8     no  southeast   1725.55
2      28    male  33.0     no  southeast   4449.46
3      33    male  22.7     no  northwest  21984.47
4      32    male  28.9     no  northwest   3866.86
...   ...     ...   ...    ...        ...       ...
1333   50    male  31.0     no  northwest  10600.55
1334   18  female  31.9     no  northeast   2205.98
1335   18  female  36.9     no  southeast   1629.83
1336   21  female  25.8     no  southwest   2007.95
1337   61  female  29.1    yes  northwest  29141.36

[1338 rows x 6 columns]

In [25]:
# icrement age
df['age'] = df['age'] + 2
df

      age     sex   bmi smoker     region  expenses
0      21  female  27.9    yes  southwest  16884.92
1      20    male  33.8     no  southeast   1725.55
2      30    male  33.0     no  southeast   4449.46
3      35    male  22.7     no  northwest  21984.47
4      34    male  28.9     no  northwest   3866.86
...   ...     ...   ...    ...        ...       ...
1333   52    male  31.0     no  northwest  10600.55
1334   20  female  31.9     no  northeast   2205.98
1335   20  female  36.9     no  southeast   1629.83
1336   23  female  25.8     no  southwest   2007.95
1337   63  female  29.1    yes  northwest  29141.36

[1338 rows x 6 columns]

In [26]:
df.describe()

               age          bmi      expenses
count  1338.000000  1338.000000   1338.000000
mean     41.207025    30.665471  13270.422414
std      14.049960     6.098382  12110.011240
min      20.000000    16.000000   1121.870000
25%      29.000000    26.300000   4740.287500
50%      41.000000    30.400000   9382.030000
75%      53.000000    34.700000  16639.915000
max      66.000000    53.100000  63770.430000