In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('insurance.csv')
df.head(10)

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86
5   31  female  25.7         0     no  southeast   3756.62
6   46  female  33.4         1     no  southeast   8240.59
7   37  female  27.7         3     no  northwest   7281.51
8   37    male  29.8         2     no  northeast   6406.41
9   60  female  25.8         0     no  northwest  28923.14

In [3]:
df.tail(6)

      age     sex   bmi  children smoker     region  expenses
1332   52  female  44.7         3     no  southwest  11411.69
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

In [4]:
df.describe()

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [6]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
expenses    float64
dtype: object

In [8]:
# handling missing values
df.isnull()

        age    sex    bmi  children  smoker  region  expenses
0     False  False  False     False   False   False     False
1     False  False  False     False   False   False     False
2     False  False  False     False   False   False     False
3     False  False  False     False   False   False     False
4     False  False  False     False   False   False     False
...     ...    ...    ...       ...     ...     ...       ...
1333  False  False  False     False   False   False     False
1334  False  False  False     False   False   False     False
1335  False  False  False     False   False   False     False
1336  False  False  False     False   False   False     False
1337  False  False  False     False   False   False     False

[1338 rows x 7 columns]

In [10]:
df.isnull().any()

age         False
sex         False
bmi         False
children    False
smoker      False
region      False
expenses    False
dtype: bool

In [11]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [13]:
df_filled = df.fillna(0)

In [5]:
# filling missing values of the column
df['bmi_fillNA'] = df['bmi'].fillna(df['bmi'].mean())
df

      age     sex   bmi  children smoker     region  expenses  bmi_fillNA
0      19  female  27.9         0    yes  southwest  16884.92        27.9
1      18    male  33.8         1     no  southeast   1725.55        33.8
2      28    male  33.0         3     no  southeast   4449.46        33.0
3      33    male  22.7         0     no  northwest  21984.47        22.7
4      32    male  28.9         0     no  northwest   3866.86        28.9
...   ...     ...   ...       ...    ...        ...       ...         ...
1333   50    male  31.0         3     no  northwest  10600.55        31.0
1334   18  female  31.9         0     no  northeast   2205.98        31.9
1335   18  female  36.9         0     no  southeast   1629.83        36.9
1336   21  female  25.8         0     no  southwest   2007.95        25.8
1337   61  female  29.1         0    yes  northwest  29141.36        29.1

[1338 rows x 8 columns]

In [6]:
df.dtypes

age             int64
sex            object
bmi           float64
children        int64
smoker         object
region         object
expenses      float64
bmi_fillNA    float64
dtype: object

In [8]:
# renaming column
df.rename(columns={'children':'kids'})

      age     sex   bmi  kids smoker     region  expenses  bmi_fillNA
0      19  female  27.9     0    yes  southwest  16884.92        27.9
1      18    male  33.8     1     no  southeast   1725.55        33.8
2      28    male  33.0     3     no  southeast   4449.46        33.0
3      33    male  22.7     0     no  northwest  21984.47        22.7
4      32    male  28.9     0     no  northwest   3866.86        28.9
...   ...     ...   ...   ...    ...        ...       ...         ...
1333   50    male  31.0     3     no  northwest  10600.55        31.0
1334   18  female  31.9     0     no  northeast   2205.98        31.9
1335   18  female  36.9     0     no  southeast   1629.83        36.9
1336   21  female  25.8     0     no  southwest   2007.95        25.8
1337   61  female  29.1     0    yes  northwest  29141.36        29.1

[1338 rows x 8 columns]

In [9]:
# change data type
df['age_new'] = df['age'].astype(float)

In [10]:
df.head(5)

,age,sex,bmi,children,smoker,region,expenses,bmi_fillNA,age_new
0,19,female,27.9,0,yes,southwest,16884.92,27.9,19.0
1,18,male,33.8,1,no,southeast,1725.55,33.8,18.0
2,28,male,33.0,3,no,southeast,4449.46,33.0,28.0
3,33,male,22.7,0,no,northwest,21984.47,22.7,33.0
4,32,male,28.9,0,no,northwest,3866.86,28.9,32.0

In [11]:
df['New Reading'] = df['bmi'].apply(lambda x:x*2)
df.head(5)

,age,sex,bmi,children,smoker,region,expenses,bmi_fillNA,age_new,New Reading
0,19,female,27.9,0,yes,southwest,16884.92,27.9,19.0,55.8
1,18,male,33.8,1,no,southeast,1725.55,33.8,18.0,67.6
2,28,male,33.0,3,no,southeast,4449.46,33.0,28.0,66.0
3,33,male,22.7,0,no,northwest,21984.47,22.7,33.0,45.4
4,32,male,28.9,0,no,northwest,3866.86,28.9,32.0,57.8

In [12]:
# data aggration and grouping

grouped_mean = df.groupby('bmi')['age'].mean()
print(grouped_mean)

bmi
16.0    18.000000
16.8    29.500000
17.2    26.000000
17.3    27.666667
17.4    22.000000
          ...
48.1    46.000000
49.1    58.000000
50.4    23.000000
52.6    22.000000
53.1    18.000000
Name: age, Length: 275, dtype: float64

In [13]:
grouped_sum = df.groupby(['age', 'region'])['bmi'].sum()
print(grouped_sum)

age  region
18   northeast     914.3
     southeast    1247.7
19   northwest     973.8
     southeast     108.3
     southwest     862.6
                   ...
63   southwest     205.4
64   northeast     135.7
     northwest     152.6
     southeast     272.5
     southwest     164.9
Name: bmi, Length: 185, dtype: float64

In [16]:
grouped_agg = df.groupby('region')['bmi'].agg(['mean', 'sum', 'count'])
grouped_agg

                mean      sum  count
region
northeast  29.176235   9453.1    324
northwest  29.201846   9490.6    325
southeast  33.359341  12142.8    364
southwest  30.596615   9943.9    325

In [22]:
# merging and joining data frames
df1 = pd.DataFrame({'Key' : ['X', 'Y', 'Z'], 'value1' : [1, 2, 3]})
df2 = pd.DataFrame({'Key' : ['X', 'W', 'Z'], 'value2' : [9, 8, 7]})

In [23]:
df1

  Key  value1
0   X       1
1   Y       2
2   Z       3

In [24]:
df2

  Key  value2
0   X       9
1   W       8
2   Z       7

In [25]:
# merge data frame on key columns

pd.merge(df1, df2, on='Key', how='inner')

  Key  value1  value2
0   X       1       9
1   Z       3       7

In [26]:
pd.merge(df1, df2, on='Key', how='outer')

  Key  value1  value2
0   W     NaN     8.0
1   X     1.0     9.0
2   Y     2.0     NaN
3   Z     3.0     7.0

In [27]:
pd.merge(df1, df2, on='Key', how='right')

  Key  value1  value2
0   X     1.0       9
1   W     NaN       8
2   Z     3.0       7

In [28]:
pd.merge(df1, df2, on='Key', how='left')

  Key  value1  value2
0   X       1     9.0
1   Y       2     NaN
2   Z       3     7.0